spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  application:
    name: sample-auth-api

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8080

jwt:
  issuer: sample-auth-api
  audience: sample-app
  access-token:
    expiration-seconds: 1800
  refresh-token:
    expiration-seconds: 2592000
